#!/bin/sh
RED='\033[0;31m';
YELLOW='\033[1;33m';
GREEN='\033[0;32m';
NC='\033[0m';

## Replace this value
BASE_BRANCH="upstream/develop";

## Replace this value
COMPARE_BRANCH=$(git rev-parse --abbrev-ref HEAD);

## Replace this value
MISSING_FILE_PATH="dependencies.txt"

if [ -z "$(git diff --name-only ${BASE_BRANCH} ${COMPARE_BRANCH} | grep \'${MISSING_FILE_PATH}\')" ]; then
  echo "${YELLOW}**********************************${NC}" 1>&2;
  echo "${YELLOW}WARNING: Not found in this push:${NC}" 1>&2;
  echo;
  echo "${MISSING_FILE_PATH}" 1>&2;
  echo;
  echo "${YELLOW}**********************************${NC}" 1>&2;
fi;

exit 0;
